dt-bindings: mailbox: add missing BFLB_IPC_DEVICE_GPIO to blfb-ipc.h
This define is needed for the bl808.dtsi to properly compile, otherwise
we get this error:
Error: arch/riscv/boot/dts/bouffalolab/bl808.dtsi:86.6-7 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Krzysztof Adamski <k@japko.eu>